version: '3.9'

services:
  redis:
    image: redis/redis-stack:7.2.0-v8
    container_name: roboqa.infra.data.redis
    restart: unless-stopped
    ports:
      - "6379:6379"
      - "8001:8001"

  tasks:
    build:
      dockerfile: Dockerfile
      context: ./
    image: roboqa.services:0.0.1
    container_name: roboqa.service.tasks
    restart: unless-stopped
    volumes:
      - ./config.dev.toml:/app/config.toml
    command: dramatiq roboqa_web.runners.worker.runner
    depends_on:
      - roboqa.infra.data.redis

  api:
    image: roboqa.services:0.0.1
    container_name: roboqa.service.api
    restart: unless-stopped
    volumes:
      - ./config.dev.toml:/app/config.toml
    command: python -m roboqa_web.runners.web.runner
    expose:
      - 2099
    ports:
      - "2099:2099"
    depends_on:
      - roboqa.services.tasks
      - roboqa.infra.data.redis
